### ISSUE TITLE
xml usage

### ISSUE THREAD

**Issue by Jdbeck66** [tdwg/abcd#19]
Is there some documentation regarding the implementation of the standard from the .xsd schema into SQL?

**Comment by DavidFichtmueller** [comment]
First of all, there is no ready to use SQL structure that corresponds to the ABCD format. Historically ABCD was designed to be an exchange format for data coming from different already existing databases. This why it is possible to express the same information in different ways, usually with one element for the combined information and one with detailed atomized values, see for instance ScientificName or PersonNames. Also since ABCD covers different types of models (see RecordBasis and KindOfUnit), some parts of the overall standard were modelled after previous existing standards, e.g. HISPID for details about herbarium specimens. So the different parts of ABCD serve different use-cases.

But there are still some recommendations that we can give you. Select the different parts of ABCD that you need and for each element decide, whether it makes sense in your context. Elements that are in repeatable containers should be modelled as separate tables in the database. 

The columns for the individual elements should match the type of schema for that element, e.g. String, Integer, Double (However coordinates should be capped to 5 or 6 digits after the decimal, see [XKCD 2170: Coordinate Precision](https://xkcd.com/2170/)).

Wherever possible use external identifiers to connect to external resources, e.g. ORCID and/or Wikidata for persons. 

In general try to use elements atomized as possible, as they can be combined during ABCD generation if needed, but when only stored combined, it is hard to separate them, when needed. 

Controlled vocabularies can be modelled by importing the terms defined by ABCD as entries in a table and refer to them. This however requires that the input interface and mechanisms need to be designed accordingly. This ensures that fields with controlled vocabularies only contain the values allowed by the standard. 

In general it might also be useful to think about the next step in how the data can later be exported back to ABCD. Our recommendation is the BioCASe Provider Software (BPS) for this. I would recommend that you already read [the documentation](https://wiki.bgbm.org/bps/index.php/Main_Page) for it and see how your design decisions might influence the later mapping steps. 

Two particular things to look out for when modelling for ABCD are the elements for higher taxonomy (element HigherTaxon) and NamedAreas (for geographic locations like counties, districts and states). HigherTaxon has the elements HigherTaxonRank and HigherTaxonName for information like the family or order of the species and not individual elements for them, like for instance DarwinCore does. The named areas are designed similarly with AreaClass and AreaName. 

I think those are the important recommendations for now. 

Let me know, if you have any further question.
Kind regards
  David
